[package]
name = "picori"
version = "0.1.1"
edition = "2021"
authors = ["Julgodis <self@julgodis.xyz>"]

repository = "https://github.com/Julgodis/picori"
license = "MIT"
readme = "README.md"
description = "Library building modding and decomplication tools for GameCube/Wii games"
keywords = ["dol", "rel", "rarc", "yaz0", "gamecube"]
categories = ["encoding", "compression", "parser-implementations"]

build = "scripts/build.rs"
publish = false

[features]
# by default, picori will be built with all features enabled
default = ["file", "compression", "encoding", "demangle", "ciso", "dol", "gcm", "rel", "yaz0", "ascii", "jis_x_0201", "shift_jis_1997", "shift_jis_2004"]

# file formats
file = []
ciso = ["file"]
gcm = ["file", "ascii", "dol"]
dol = ["file"]
rel = ["file"]

# compression
compression = []
yaz0 = ["compression"]

# demangling
# TODO: add demangling features
demangle = []

# encoding
encoding = []
ascii = ["encoding"]
jis_x_0201 = ["encoding"]
shift_jis_1997 = ["encoding", "jis_x_0201"]
shift_jis_2004 = ["encoding", "jis_x_0201"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"

[build-dependencies]
thiserror = "1.0"
