[package]
name = "picori"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Julgodis/picori"

readme = "README.md"
authors = ["Julgodis <self@julgodis.xyz>"]
description = "Library building modding and decomplication tools for GameCube/Wii games"
keywords = ["dol", "rel", "rarc", "yaz0", "gamecube"]
categories = ["encoding", "compression", "parsing", "modding", "deomp"]
publish = false
build = "scripts/build.rs"

[dependencies]
thiserror = "1.0"
itertools = "0.10"

[build-dependencies]
thiserror = "1.0"
