name: Build & Test & Fmt & Clippy

on:
  push:
    branches:
      - master
    paths-ignore: 
      - 'coverage/**'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: picori
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy, llvm-tools-preview

      - name: build
        run: cargo build --verbose

      - name: test
        run: cargo test --verbose

      - name: fmt
        run: cargo fmt -- --check --verbose

      - name: clippy
        run: cargo clippy --verbose -- -D warnings